## Environment settings
defaults: &defaults
  host: localhost
  port: 3000
  protocol: http


development:
  <<: *defaults

test:
  <<: *defaults

production:
  host: swat-sandbox.herokuapp.com
  port: 443
  protocol: https
  <<: *defaults